name: EarnZood Bot

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-bot:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot==22.5

      - name: Check bot files
        run: |
          echo "Checking files..."
          ls -la
          echo "Checking bot.py..."
          grep -n "پنل مدیریت" bot.py || true

      - name: Run EarnZood Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python bot.py
